export interface AgentProfile {
  id: string;
  full_name: string;
  company_name: string;
  license_number: string;
  license_state: string;
  avatar_url: string;
  location_state: string;
  location_city: string;
  total_listings: number;
  price_min: number;
  price_max: number;
  acres_min: number;
  acres_max: number;
  years_experience: number;
  specialties: string[];
  states_served: string[];
  bio: string;
  phone: string;
  website: string;
  is_verified: boolean;
}

export const MOCK_AGENTS: AgentProfile[] = [
  {
    id: 'agent-1',
    full_name: 'Jason Williams',
    company_name: 'Plantation Properties & Land Investments',
    license_number: 'TX-0567832',
    license_state: 'TX',
    avatar_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=300&q=80',
    location_state: 'Texas',
    location_city: 'Austin',
    total_listings: 102,
    price_min: 15000,
    price_max: 12800000,
    acres_min: 0.51,
    acres_max: 2662,
    years_experience: 12,
    specialties: ['Ranch Land', 'Hunting Land', 'Farmland'],
    states_served: ['Texas', 'Oklahoma', 'New Mexico'],
    bio: 'With over 12 years specializing in Texas ranch and hunting land, Jason has helped more than 500 buyers and sellers close successful deals across the Lone Star State. His deep knowledge of Texas land laws, water rights, and agricultural zoning makes him one of the most trusted land specialists in the region.',
    phone: '(512) 555-0123',
    website: 'https://plantationproperties.com',
    is_verified: true,
  },
  {
    id: 'agent-2',
    full_name: 'Nancy Lawrence',
    company_name: 'Lawrence Realty Group',
    license_number: 'FL-BK3456789',
    license_state: 'FL',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&q=80',
    location_state: 'Florida',
    location_city: 'Orlando',
    total_listings: 122,
    price_min: 70000,
    price_max: 4200000,
    acres_min: 0,
    acres_max: 422,
    years_experience: 9,
    specialties: ['Waterfront Property', 'Residential Lots', 'Commercial Land'],
    states_served: ['Florida', 'Georgia', 'South Carolina'],
    bio: 'Nancy is a Florida-licensed broker with 9 years helping clients find waterfront parcels, beachfront lots, and investment land across the Sunshine State. She specializes in coastal properties and residential development lots near Florida\'s fastest-growing cities.',
    phone: '(407) 555-0187',
    website: 'https://lawrencerealtyfl.com',
    is_verified: true,
  },
  {
    id: 'agent-3',
    full_name: 'Andy Flack',
    company_name: 'HomeLand Properties',
    license_number: 'MT-RRE-12847',
    license_state: 'MT',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&q=80',
    location_state: 'Montana',
    location_city: 'Billings',
    total_listings: 149,
    price_min: 44000,
    price_max: 12000000,
    acres_min: 0.1,
    acres_max: 2356,
    years_experience: 18,
    specialties: ['Ranch Land', 'Mountain Property', 'Hunting Land'],
    states_served: ['Montana', 'Wyoming', 'Idaho'],
    bio: 'Andy has been selling Montana ranch and mountain land for 18 years. His expertise in remote parcels, water rights, mineral rights, and conservation easements is unmatched in Big Sky Country. He has brokered some of the largest ranch transactions in the state.',
    phone: '(406) 555-0244',
    website: 'https://homelandproperties.com',
    is_verified: true,
  },
  {
    id: 'agent-4',
    full_name: 'Maria Rodriguez',
    company_name: 'Southwest Land Brokers',
    license_number: 'AZ-BR-123456',
    license_state: 'AZ',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&q=80',
    location_state: 'Arizona',
    location_city: 'Phoenix',
    total_listings: 88,
    price_min: 8500,
    price_max: 3500000,
    acres_min: 1,
    acres_max: 1840,
    years_experience: 7,
    specialties: ['Desert Land', 'Raw / Undeveloped Land', 'Horse Property'],
    states_served: ['Arizona', 'New Mexico', 'Nevada'],
    bio: 'Maria specializes in Southwest desert land, off-grid parcels, and horse properties throughout Arizona. With 7 years of experience, she has a deep understanding of desert zoning laws, water access issues, and the unique challenges of purchasing raw land in arid climates.',
    phone: '(602) 555-0198',
    website: 'https://southwestlandbrokers.com',
    is_verified: true,
  },
  {
    id: 'agent-5',
    full_name: 'Robert Calloway',
    company_name: 'Appalachian Land & Realty',
    license_number: 'TN-258147',
    license_state: 'TN',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&q=80',
    location_state: 'Tennessee',
    location_city: 'Nashville',
    total_listings: 74,
    price_min: 12000,
    price_max: 2800000,
    acres_min: 0.5,
    acres_max: 1200,
    years_experience: 11,
    specialties: ['Wooded / Timber Land', 'Hunting Land', 'Mountain Property'],
    states_served: ['Tennessee', 'Kentucky', 'North Carolina', 'Virginia'],
    bio: 'Robert has spent 11 years helping buyers find wooded retreats, hunting camps, and mountain cabins across the Appalachian region. He is known for his ability to identify hidden-value timber tracts and recreational properties that traditional agents overlook.',
    phone: '(615) 555-0311',
    website: 'https://appalachianland.com',
    is_verified: false,
  },
  {
    id: 'agent-6',
    full_name: 'Sarah Johnson',
    company_name: 'Great Plains Land Co.',
    license_number: 'KS-BR-987654',
    license_state: 'KS',
    avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&q=80',
    location_state: 'Kansas',
    location_city: 'Wichita',
    total_listings: 93,
    price_min: 25000,
    price_max: 8500000,
    acres_min: 2,
    acres_max: 5000,
    years_experience: 14,
    specialties: ['Farmland / Agricultural', 'Ranch Land', 'Raw / Undeveloped Land'],
    states_served: ['Kansas', 'Nebraska', 'Oklahoma', 'Missouri'],
    bio: 'Sarah is one of the most respected agricultural land specialists in the Great Plains. With 14 years brokering farm and ranch deals across four states, she understands crop yields, soil reports, drainage tiles, and everything that makes productive farmland valuable.',
    phone: '(316) 555-0422',
    website: 'https://greatplainsland.com',
    is_verified: true,
  },
  {
    id: 'agent-7',
    full_name: 'Marcus Thompson',
    company_name: 'Colorado Mountain Realty',
    license_number: 'CO-FA-100234',
    license_state: 'CO',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&q=80',
    location_state: 'Colorado',
    location_city: 'Denver',
    total_listings: 67,
    price_min: 55000,
    price_max: 15000000,
    acres_min: 1,
    acres_max: 1500,
    years_experience: 8,
    specialties: ['Mountain Property', 'Ranch Land', 'Recreational Land'],
    states_served: ['Colorado', 'Wyoming', 'Utah'],
    bio: 'Marcus focuses exclusively on Colorado mountain land and ski country parcels. His 8 years of mountain real estate experience includes high-altitude parcels, mining claims, and conservation easements. He has helped hundreds of buyers find their perfect Colorado escape.',
    phone: '(720) 555-0567',
    website: 'https://coloradomountainrealty.com',
    is_verified: true,
  },
  {
    id: 'agent-8',
    full_name: 'Patricia Moore',
    company_name: 'Georgia Land Specialists',
    license_number: 'GA-247892',
    license_state: 'GA',
    avatar_url: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=300&q=80',
    location_state: 'Georgia',
    location_city: 'Atlanta',
    total_listings: 110,
    price_min: 18000,
    price_max: 6200000,
    acres_min: 0.25,
    acres_max: 800,
    years_experience: 15,
    specialties: ['Hunting Land', 'Farmland / Agricultural', 'Residential Lots'],
    states_served: ['Georgia', 'Alabama', 'South Carolina', 'Florida'],
    bio: 'Patricia has been one of Georgia\'s top land agents for 15 years. She specializes in hunting tracts in the Georgia Piedmont, timber and farmland in South Georgia, and residential development lots near Atlanta\'s expanding suburbs.',
    phone: '(404) 555-0678',
    website: 'https://georgialandspecialists.com',
    is_verified: true,
  },
  {
    id: 'agent-9',
    full_name: 'Daniel Brooks',
    company_name: 'Pacific Northwest Land Group',
    license_number: 'OR-200345-A',
    license_state: 'OR',
    avatar_url: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=300&q=80',
    location_state: 'Oregon',
    location_city: 'Portland',
    total_listings: 58,
    price_min: 35000,
    price_max: 9800000,
    acres_min: 1,
    acres_max: 3200,
    years_experience: 10,
    specialties: ['Wooded / Timber Land', 'Waterfront Property', 'Recreational Land'],
    states_served: ['Oregon', 'Washington', 'Idaho'],
    bio: 'Daniel specializes in Pacific Northwest timber land, waterfront acreage, and recreational properties. His 10-year career in Oregon land sales has given him exceptional knowledge of timber cruise values, riparian rights, and environmental regulations unique to the Pacific Northwest.',
    phone: '(503) 555-0789',
    website: 'https://pnwlandgroup.com',
    is_verified: false,
  },
];

export function formatPrice(n: number): string {
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000)     return `$${Math.round(n / 1_000)}K`;
  return `$${n.toLocaleString()}`;
}
