// Mock data — used for development until Supabase is connected
import { Listing } from '../types';

export const mockListings: Listing[] = [
  {
    id: '1',
    seller_id: 'seller1',
    title: 'Rolling Ranch Property',
    description: 'Beautiful 40-acre rolling ranch land in the heart of Texas Hill Country. Features mature oak trees, seasonal creek, and excellent road access. Perfect for cattle, horses, or a weekend getaway. Electricity available at the road.',
    acres: 40,
    price: 89000,
    price_per_acre: 2225,
    state: 'Texas',
    county: 'Hill County',
    zip_code: '76457',
    type: 'Ranch Land',
    status: 'active',
    images: [],
    features: ['Road Access', 'Electricity Available', 'Creek', 'Mature Trees'],
    created_at: '2025-01-10T00:00:00Z',
    updated_at: '2025-01-10T00:00:00Z',
  },
  {
    id: '2',
    seller_id: 'seller2',
    title: 'Mountain Hunting Retreat',
    description: 'Prime 10-acre hunting property in Glacier County, Montana. Surrounded by public land on three sides, giving you access to thousands of acres. Whitetail deer, elk, and turkey abound. Cabin-ready site with spring water.',
    acres: 10,
    price: 45000,
    price_per_acre: 4500,
    state: 'Montana',
    county: 'Glacier County',
    zip_code: '59436',
    type: 'Hunting Land',
    status: 'active',
    images: [],
    features: ['Spring Water', 'Hunting Access', 'Adjacent Public Land', 'Cabin Site'],
    created_at: '2025-01-12T00:00:00Z',
    updated_at: '2025-01-12T00:00:00Z',
  },
  {
    id: '3',
    seller_id: 'seller3',
    title: 'Waterfront Residential Lot',
    description: 'Stunning 5-acre lot in Alachua County Florida with 200ft of lake frontage. Cleared and ready to build your dream home. All utilities available. Quiet neighborhood, no HOA.',
    acres: 5,
    price: 28000,
    price_per_acre: 5600,
    state: 'Florida',
    county: 'Alachua County',
    zip_code: '32615',
    type: 'Residential Lots',
    status: 'active',
    images: [],
    features: ['Lake Frontage', 'Utilities Available', 'Cleared', 'No HOA'],
    created_at: '2025-01-14T00:00:00Z',
    updated_at: '2025-01-14T00:00:00Z',
  },
  {
    id: '4',
    seller_id: 'seller1',
    title: 'High Country Mountain Land',
    description: 'Breathtaking 100-acre mountain property in Summit County, Colorado. Stunning views in every direction. Borders national forest, incredible wildlife. Owner financing available.',
    acres: 100,
    price: 350000,
    price_per_acre: 3500,
    state: 'Colorado',
    county: 'Summit County',
    zip_code: '80443',
    type: 'Mountain Property',
    status: 'active',
    images: [],
    features: ['National Forest Border', 'Owner Financing', 'Mountain Views', 'Wildlife'],
    created_at: '2025-01-08T00:00:00Z',
    updated_at: '2025-01-08T00:00:00Z',
  },
  {
    id: '5',
    seller_id: 'seller4',
    title: 'Wooded Timber Acreage',
    description: '20 acres of mature hardwood timber in Grundy County, Tennessee. Mix of oak, hickory, and poplar. Great hunting, excellent timber investment, or build your off-grid cabin.',
    acres: 20,
    price: 62000,
    price_per_acre: 3100,
    state: 'Tennessee',
    county: 'Grundy County',
    zip_code: '37367',
    type: 'Wooded / Timber Land',
    status: 'active',
    images: [],
    features: ['Mature Timber', 'Hunting', 'Creek', 'Gravel Road Access'],
    created_at: '2025-01-16T00:00:00Z',
    updated_at: '2025-01-16T00:00:00Z',
  },
  {
    id: '6',
    seller_id: 'seller5',
    title: 'Desert Sunset Acreage',
    description: 'Incredible 15-acre desert property in Luna County, New Mexico. Panoramic views of three mountain ranges. Off-grid solar setup included. Very low property taxes.',
    acres: 15,
    price: 35000,
    price_per_acre: 2333,
    state: 'New Mexico',
    county: 'Luna County',
    zip_code: '88021',
    type: 'Desert Land',
    status: 'active',
    images: [],
    features: ['Solar Setup Included', 'Mountain Views', 'Low Taxes', 'Well Permitted'],
    created_at: '2025-01-18T00:00:00Z',
    updated_at: '2025-01-18T00:00:00Z',
  },
  {
    id: '7',
    seller_id: 'seller2',
    title: 'Prime Oklahoma Farmland',
    description: 'Productive 80-acre farm in Grady County, Oklahoma. Currently in wheat production. Rich dark soil, excellent water rights, irrigation system in place. 10 minutes to town.',
    acres: 80,
    price: 192000,
    price_per_acre: 2400,
    state: 'Oklahoma',
    county: 'Grady County',
    zip_code: '73044',
    type: 'Farmland / Agricultural',
    status: 'active',
    images: [],
    features: ['Irrigation System', 'Water Rights', 'Rich Soil', 'Currently Farmed'],
    created_at: '2025-01-20T00:00:00Z',
    updated_at: '2025-01-20T00:00:00Z',
  },
  {
    id: '8',
    seller_id: 'seller3',
    title: 'Recreational ATV Paradise',
    description: '25 acres of rolling ATV / recreational land in Ozark County, Missouri. Trails already cut through property. Pond stocked with bass and catfish. Seller financing available.',
    acres: 25,
    price: 55000,
    price_per_acre: 2200,
    state: 'Missouri',
    county: 'Ozark County',
    zip_code: '65733',
    type: 'Recreational Land',
    status: 'active',
    images: [],
    features: ['ATV Trails', 'Stocked Pond', 'Seller Financing', 'Electric Available'],
    created_at: '2025-01-22T00:00:00Z',
    updated_at: '2025-01-22T00:00:00Z',
  },
];
